### ISSUE TITLE
`npm run bundle` fails

### ISSUE THREAD

**Issue by nicolaspayot** [ngVue/ngVue#3]
Here's what I get when I try to run the `bundle` task:
```
> ngVue@0.1.1 bundle /home/npayot/dev/ngVue
> BABEL_ENV=build rollup -c

resolve failed:  { Error: Cannot find module 'caniuse-db'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/home/npayot/dev/ngVue/node_modules/require-relative/index.js:30:17)
    at resolve (/home/npayot/dev/ngVue/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/npayot/dev/ngVue/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/npayot/dev/ngVue/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/npayot/dev/ngVue/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/npayot/dev/ngVue/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/npayot/dev/ngVue/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12) code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/home/npayot/dev/ngVue/node_modules/require-relative/index.js:30:17)
    at resolve (/home/npayot/dev/ngVue/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/npayot/dev/ngVue/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/npayot/dev/ngVue/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/npayot/dev/ngVue/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/npayot/dev/ngVue/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/npayot/dev/ngVue/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/npayot/dev/ngVue/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at preflightCheck (/home/npayot/dev/ngVue/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:44:25)
    at Object.transform$1 [as transform] (/home/npayot/dev/ngVue/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:117:18)
    at /home/npayot/dev/ngVue/node_modules/rollup/src/utils/transform.js:19:35 code: 'MODULE_NOT_FOUND' } babel-runtime
Treating 'babel-helper-vue-jsx-merge-props' as external dependency
No name was provided for external module 'babel-helper-vue-jsx-merge-props' in options.globals – guessing '_mergeJSXProps'
```
I tried to install modules `caniuse-db` and `babel-plugin-transform-runtime` but nothing better came out.
I'm using node v7.0.0 and have the same output with node 6.5.0. If you have any hints, I'd be more than happy to help.

**Comment by dorayx** [comment]
oh I encountered the same issue after updating npm packages ...

**Comment by dorayx** [comment]
@nicolaspayot I updated all the packages and this issue should be fixed now ;-)

**Comment by nicolaspayot** [comment]
Awesome, thank you!
